### ISSUE TITLE
Questions and questions

### ISSUE THREAD

**Issue by yuanjin2661** [mitbook/mitbook-mountain#9]
@pengzhengfa  How to use this framework and what is its principle? Can you tell me about it

**Comment by pengzhengfa** [comment]
@yuanjin2661  If you look at the mitbook-test project and the project documents, as for the principle, you can first understand the Seata framework and then understand the framework

**Comment by BobSimon** [comment]
Looking at the feeling is very tall on the appearance, I have not seen the source code, let alone the sea TA source code, a look dizzy feeling
